name: CI workflow

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        preset: [preset1, preset1-hq]

    steps:
      - name: Checkout source code
        uses: actions/checkout@v7

      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Install dependencies
        run: nix profile add nixpkgs#shellcheck

      - name: Bootstrap the build system
        run: autoreconf --install --force

      - name: Configure
        run: ./configure --with-preset=${{ matrix.preset }}

      - name: Build
        run: make

      - name: Verify generated files
        run: test -f settings.ini

      - name: Run Distcheck (The Gold Standard)
        run: make distcheck
